version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'npm'
      - 'dependencies'
    prefix: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: 'node'
        versions:
          - '< 14'
