name: test

on:
  push:
    branches:
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup
        with:
          node-version-file: '.nvmrc'

  lint:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Lint project
        run: pnpm run lint

  vitest:
    runs-on: ubuntu-latest
    needs:
      - setup
      - lint
    steps:
      - name: Run vitest
        run: pnpm run test:vitest

  # playwright:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - setup
  #     - lint
  #   steps:
  #     - name: Run playwright
  #       run: pnpm run test:playwright

  coverage:
    runs-on: ubuntu-latest
    needs:
      - setup
      - lint
      - vitest
      # - playwright
    steps:
      - name: Gather test coverage
        run: |
          SUMMARY="$(npm run test:coverage | tail -2 | head -1)"
          TOKENS=($SUMMARY)
          echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV

      - name: Create badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 46d409f23d2b17672adfa2dfe9b6b1f0
          filename: coverage.svg
          label: coverage
          message: ${{ env.COVERAGE }}
          color: lightgrey
